#!/bin/bash
set -e

#Ensure in scripts directory
cd $( dirname "${BASH_SOURCE[0]}" )/..

VERSION=$(git describe --tags --always)

echo "Version: $VERSION"

if [[ -z "${HOST}" ]]; then
    HOST=pi@192.168.1.200
fi
DIR=/home/pi/tree

echo "Host: $HOST"

./scripts/compile-and-copy

echo "Setting ownership..."
ssh $HOST "sudo chown pi:pi $DIR /home/pi -Rf"

echo "Installing requirements..."
ssh $HOST "cd $DIR && yarn install --production"

# echo "Adding version"
# ssh $HOST "echo '$(echo "module.exports = \"$VERSION\";")' > $DIR/src/version.js"

echo "Restarting service..."
RESULT=$(ssh $HOST "sudo killall node")
if [[ $RESULT = *"ERROR"* ]]; then
    echo "Error starting service! - $RESULT"
    exit -1
fi

exit 0